CONF = {
    "APP_KEY": "YOUR-TWITTER-APP_KEY",
    "APP_SECRET": "YOUR-TWITTER-APP_SECRET",
    "OAUTH_TOKEN": "YOUR-TWITTER-OAUTH_TOKEN",
    "OAUTH_TOKEN_SECRET": "YOUR-TWITTER-OAUTH_TOKEN_SECRET",
    "KEYWORD": "YOUR-SEARCH-KEYWORD"
}